// Auth

export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'

export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_FINISH = 'SIGNUP_FINISH'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const SIGNIN_START = 'SIGNIN_START'
export const SIGNIN_FINISH = 'SIGNIN_FINISH'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START'
export const RESET_PASSWORD_FINISH = 'RESET_PASSWORD_FINISH'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const SIGNOUT = 'SIGNOUT'

// Account

export const EDIT_PROFILE_START = 'EDIT_PROFILE_START'
export const EDIT_PROFILE_FINISH = 'EDIT_PROFILE_FINISH'
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL'

// Channels

export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL'
export const SET_PRIVATE_CHANNEL = 'SET_PRIVATE_CHANNEL'

export const FETCH_NEW_CHANNELS_START = 'FETCH_NEW_CHANNELS_START'
export const FETCH_NEW_CHANNELS_FINISH = 'FETCH_NEW_CHANNELS_FINISH'
export const FETCH_NEW_CHANNELS_FAIL = 'FETCH_NEW_CHANNELS_FAIL'

export const GET_CHANNELS_START = 'GET_CHANNELS_START'
export const GET_CHANNELS_FINISH = 'GET_CHANNELS_FINISH'
export const GET_CHANNELS_FAIL = 'GET_CHANNELS_FAIL'

export const ADD_CHANNEL_START = 'ADD_CHANNEL_START'
export const ADD_CHANNEL_FINISH = 'ADD_CHANNEL_FINISH'
export const ADD_CHANNEL_FAIL = 'ADD_CHANNEL_FAIL'

// Messages

export const GET_MESSAGES_START = 'GET_MESSAGES_START'
export const GET_MESSAGES_FINISH = 'GET_MESSAGES_FINISH'
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL'

export const FETCH_NEW_MESSAGES_START = 'FETCH_NEW_MESSAGES_START'
export const FETCH_NEW_MESSAGES_FINISH = 'FETCH_NEW_MESSAGES_FINISH'
export const FETCH_NEW_MESSAGES_FAIL = 'FETCH_NEW_MESSAGES_FAIL'

export const ADD_MESSAGE_START = 'ADD_MESSAGE_START'
export const ADD_MESSAGE_FINISH = 'ADD_MESSAGE_FINISH'
export const ADD_MESSAGE_FAIL = 'ADD_MESSAGE_FAIL'

// Modals

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
